### ISSUE TITLE
[Feature]: Add functionality to add profile pictures to accounts

### ISSUE THREAD

**Issue by tobisupreme** [AltCamp/altcampv1-backend#100]
### The Problem

No support for profile photos

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by muttaqin1** [comment]
Hello @tobisupreme, 
Can i contribute on this issue?

**Comment by misspee007** [comment]
Hi! @muttaqin1, I was already working on this, but I forgot to indicate. Sorry about that!

**Comment by muttaqin1** [comment]
can i contribute on this #114 ?
you can assign me on that.
