### ISSUE TITLE
[Feature]: Create endpoint to serve tracks available on AltCamp

### ISSUE THREAD

**Issue by tobisupreme** [AltCamp/altcampv1-backend#107]
### The Problem

Create an endpoint to serve tracks available on AltCamp

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jhhornn** [comment]
I want to jump on this but I need to know where the endpoint will be needed?
So I can know where to start @tobisupreme

**Comment by tobisupreme** [comment]
Thanks for indicating interest!

This endpoint is needed to serve the options presented to the user on the registration screen.

![Tracks on AltCamp](https://i.ibb.co/9vbMPCn/Screenshot-2023-07-24-18-31-24.png)

Currently, they are _hard coded_ on the Front End.
