### ISSUE TITLE
[Bug]: Paginated bookmark data not in correct order

### ISSUE THREAD

**Issue by Boye95** [AltCamp/altcampv1-backend#192]
### What happened?

I queried the bookmarks endpoint for bookmarks and the data I got didn't have the latest bookmark at the top of the list.

### Expected behavior

Bookmarks from the API should be returned in reverse i.e showing the data from the latest to the oldest

### Your Environment

Nodejs

### Steps to Reproduce the Behavior

1. Add a bookmark
2. Go to the bookmark page to see your bookmarks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tobisupreme** [comment]
Hi @Boye95. I understand the bug you have described. I can take a look at this 🚀

**Comment by Boye95** [comment]
Thanks, Tobi 🙌
