### ISSUE TITLE
[Bug]: New bookmark returns Conflict Error

### ISSUE THREAD

**Issue by just-talis** [AltCamp/altcampv1-backend#207]
### What happened?

When you attempt to create a new bookmark with a unique message, the backend api still returns a conflict error.

### Expected behavior

successful response

### Your Environment

Mac / Chrome

### Steps to Reproduce the Behavior

Call the https://the-altcamp.onrender.com/bookmarks using the POST method with unique message.

`{"title":"This is a unique message","postId":"64a7d1864fcabad414705bf2","postType":"Question"}`

### Relevant log output

```shell
{"statusCode":409,"message":"Bookmark already exists!","error":"Conflict"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tobisupreme** [comment]
Hi, @just-talis!

What you have described is the intended behaviour. It is by design that you can only bookmark a resource one time.

For example, if you attempt to create two bookmarks with the same `postId`, the API responds with a `409 Conflict`.
