### ISSUE TITLE
[Feature]: Implement bulk action on Bookmarks(bulk delete bookmarks)

### ISSUE THREAD

**Issue by Boye95** [AltCamp/altcampv1-backend#219]
### The Problem

Users who bookmark contents on the platform can only delete/remove bookmarks one at a time. It becomes stressful when the user wants to delete/remove multiple bookmarks simultaneously.

### How to Fix It

The API should have a ```deleteMultipleBookmarks``` endpoint that will take ```ids``` of the bookmarks that the user wants to delete/remove as part of the request body in an array and deletes those bookmarks simultaneously.

A sample request from the frontend using RTK-Query
```
deleteBookmark: builder.mutation({
      query: () => ({
        url: '/deleteMultipleBookmarks,
        method: 'DELETE',
        body: {
            ids: ['1234', '35433', '98765']
       }
      }), 
}),
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tobisupreme** [comment]
Thanks. We can expose an API that will accept an array of bookmark IDs. I can work on this
