### ISSUE TITLE
[Feature]: Add isBookmarked property to all query/mutation response objects for all contents

### ISSUE THREAD

**Issue by Boye95** [AltCamp/altcampv1-backend#222]
### The Problem

When performing mutations and queries on contents(post, question, comment, answer) the response object for a successful query/mutation should be consistent. Currently, queries that invalidate each other like upvoting/liking of a post rely on the response object of the upvote query and serve as the new source of data for the post. This works when the data are consistent across queries and mutations.

This is the current structure of a response object for query/mutation that's fetching content directly
```
{
    "statusCode": 200,
    "message": "Request Successful!",
    "data": {
        "_id": "....",
        "content": "...",
        "upvotes":  ...,
        "upvotedBy": [
            ...
        ],
        "author": {
           ...
        },
        "comments": [
            "..."
        ],
        "createdAt": "1",
        "updatedAt": "1",
        "__v": ...,
        "tags": []
    }
}
```

### How to Fix It

The response object should add `isBookmarked` property  as it is in the object below
```
{
    "statusCode": 200,
    "message": "Request Successful!",
    "data": {
        "_id": "....",
        "content": "...",
        "upvotes":  ...,
        "upvotedBy": [
            ...
        ],
        "author": {
           ...
        },
        "comments": [
            "..."
        ],
        "createdAt": "1",
        "updatedAt": "1",
        "__v": ...,
        "tags": [],
         "isBookmarked": true
    }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tobisupreme** [comment]
This is interesting. I would like to try to make this happen
