### ISSUE TITLE
[Feature]: Bookmark contents using query params as a means of passing data to the API

### ISSUE THREAD

**Issue by Boye95** [AltCamp/altcampv1-backend#227]
### The Problem

The current endpoint for creating a bookmark requires a request body that has `postType`, `title`, and `postId`. The new UI and flow being worked on the Frontend won't accommodate and supply some of these data anymore and therefore they will become redundant.

The current approach:

`POST` `/bookmarks`

Request Body
```
{
    "title": "How to get home",
    "postId": "12345",
    "postType": "Post"
}
```

### How to Fix It

The new approach should be:

`POST` `/bookmarks?postId=id-of-content-to-bookmark&postType=postType`
where postType is one of  `'Answer'` ,  `'Comment'` , `'Post'`, or  `'Question'`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tobisupreme** [comment]
Hi Boye! I gotcha!

**Comment by Boye95** [comment]
> Hi Boye! I gotcha!

I trust you
