### ISSUE TITLE
🐛: Continuous logging of Redis error when env keys are missing  

### ISSUE THREAD

**Issue by Olatisunkanmi** [AltCamp/altcampv1-backend#232]
### What happened?

when I start my server, Redis  continuously throws error when my env keys are missing. Logs twice, every second. 

### Expected behavior

Like every other db, It should log only once when I start my server

### Your Environment

Fedora 38

### Steps to Reproduce the Behavior

1. Start your server without your redis config set in your env 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tobisupreme** [comment]
Nice spot.

What fixes do you propose?

**Comment by Olatisunkanmi** [comment]
I think it should act like any other DB. 
when my server starts, it should log the error once and when I try to write/read from the DB, it should throw an error

**Comment by tobisupreme** [comment]
That sounds great. We can do that 😁

**Comment by Olatisunkanmi** [comment]
Hi, @tobisupreme I think the problems, is a little deeper than. The error logs continuously because the cache tries to establish connection even though the env file is missing.
