### ISSUE TITLE
Cannot read properties of undefined (reading 'host')

### ISSUE THREAD

**Issue by Olatisunkanmi** [AltCamp/altcampv1-backend#236]
### Contact Details

igbasanolasunkanmi080@gmail.com 

### What happened?

uncaught error as soon the server starts

see error log below:
 AltCamp-v1-backend/src/mailer/mailerService.js:8
  host: smtpConfig.host,
                   ^
TypeError: Cannot read properties of undefined (reading 'host')

### Expected behavior

Server should start provided all required env keys are provided

### Your Environment

Fedora 38

### Steps to Reproduce the Behavior

Try cloing the repo afresh

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tobisupreme** [comment]
Hi @Olatisunkanmi!

```
AltCamp-v1-backend/src/mailer/mailerService.js:8
host: smtpConfig.host,
^
```
The error log indicates that the configuration for the smtp is missing. Please refer to the [`example.env`](https://github.com/AltCamp/altcampv1-backend/blob/dev/example.env) for the variables needed to run the local development server.

These are required for the mail service to function:
![variables for smtp configuration](https://i.ibb.co/mcWVLJx/Screenshot-20231002-173430.png)

Gmail provides smtp credentials that you can use in your local environment. You can also checkout services like Zohomail!

Perhaps we can extend the readmes with this information?
